# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "d18cb8b94397b83ae8e64bb31889875ee6f92262411f9d81800320d1e508c672U2FsdGVkX1+fJqnyN5LdiUG122L4pwWbozYzKrg3oXt2Bzo7zr2bb9FCFoj3tMUGmI6RjmywhcVDs2HIoxTp1s489IQtMhw9jbZZxMASTpfikkhPw+fs6bVKwzlnWU2zLB2CbyW/7dOrTBoQUtDcsSvcO0fmLdZIvDO6tMYLddf6ZIQaJaH8j5g5/b5o6JwGiC+VrAk54/8bZlAC0R7VVoCqUYqY8MUXVwT+M7erKY4wj7Nm4ZrrSt3Z+3MvFfy00G3387tKKktG/V0NYxj/teJ8IZRwZ/NcmUOqYcOnBkvQNHZnTIOGFdQRbAcPK+ssU7eJD3oFve25F++MQNfguausVTKyyFYPi1MLiBfza5Ln4xX28rKYGcC82gq1D7Y7W7ON/lCRScot8Q1nIDEf6DeD82GIQkKD0Mw0EyZKgox1JPbR4nlR8r9W2Tt1at2RSHDDRbVCqbHip4gECdtrnBsHOTbpk6MeyYggOCTp/YfpK3oKDLisjEoxNUjU3DckwEal++U+50BybcLItJVC+GsZaXV6u5VoMTqRH6salbq5hpBIrfSTwz34GMIzThevKqrgCdSW7qcGSe/I+h4PzLlqCT+xjg7Dqp6gn7q669oP1v5QwHTAH5Nsl1BQgTTZ7FjTBFbvSfLm+yDkESX0qPFZyiS9USDBHB5VXXABPR7I0iseA+o+8xeK/KGHhEVKS44Wp92uLKGGNj4eLjRbYcIkP9KaqfK9yqLs2qRQ4gGuDjM3QK4lGqD1FxYpbgJ66gFIfhI26oEOCjldw1hK/l2UBuWp+LwMwy7WiKsm8UlF8o6i413ZLtL2HQRVcaKEeNCML9lCvk5R5cCYf4frM1t7PS96oSpubIX/Gvys0s5oSDY0H1aNHK6vtAJaUbr0kBVrGhWAY73flgL7UPxtUOjqpjffRxr4smamftTz1XkliB9eeLJ0OViNboNeO8XTVMhSSHPQiq0dlfJLY6bLVKtAael6TmAE7lP1v+Xw1lEIZpzrya4hyI1DiBZpJI4+HSLtqz5+V95+P8EPd/RedN6kgjNZErC7rQimwtwQ9LOQ+/kITPEeLQWxHv83KZz4mZh/kO+SwloluhKlg92MqVjnWeFFi650AwrURA7HNWzfMGCxsP5T2nglmJRdyUDeq/FPiJh79geIxMJOtX4WQG3LC4N8xttdI3X4mZyxGdXhGDIe695RgDX7iRtDCwVypQvrK0sOOOtioeR8xICZR+qyKQ6TJjX7FypovSvZ4RL+2bDNOyk+mHylZYQANhJzzmmO71fK1G3zv6suQhby5P0/02xSXWp5dNuZ5vcCSLJUnJlwPBxHikJzMCCX+ps/y999ifSJhVS/vMe9QXYKpSYFutnAeUj44jmUMCL9Or+peUuO7OId5A0supg3PI79a52Km2y8jULSprFSXn3SPe5Fv5ColKzKVVfB3gkXoCn8SrsHXMUT4xmR1l2KU6VN5lKpDgpftHaPi2jXJXgphpdmNYP9RdcGYU46gB/ETUDMr2GI48GzybY1ial6fg6j0gA5zGsbfznGaO6HAaTxwLyQIKbZ5TuHGAWRQIUfLufjxzCKiGeZ1ybWSbC0Tb18K0TMGR9ieBkDDeWZLModqxLzDwXZfpkw3mTR7mqNnEqUtSTpFAbeqVY/4kTwo6jCju8aUTbRqLlWhNI+H7m77lfQUeTZJyx2WiPRGkbU5R121wpzLGPPsrT+ObCS5+uR3LtWSETrXaqW68EBuIUwP6lFBpACyUUwmzDREwgiPZ9pELVZnIu1OzZrrRUd9TzJfLzXRJn2L9hvfNiAeaE6bsf1oWKPZNl4TDMENHdC+N4F3xPDXUUV/AN9okIzL64CBK1IB7zlwETj8hfmFnbnKpw6MLndGdeQrUCtjDhJ6vdBUUwIt1fkrmwrtqvQ9Uh+UQzarMkydavgteDUsy5HHcJ5dTKbUYyC9TeBvczCOEp3WzULSBKETkVA5Wwu5YtfdBLZ8zzLIRfjwNupsHZvHBhvhTjhkUnwwlpHNgqSsSmkFaDElkwT0sVjq02lLlcLSgrQ4PFTf1MQISU/YyQ0DhIs1yRTIOVQ88PnJw+dOFdeG4wlLpvI/4BfCxB1XUQ2EQ0vS25fu14y8YinlVgHLDzLOlby9fqbXuIeNJQ0eqCaUdzLGWovzUH+CvllpKg1stnOb8qicgFlZ86z9DTNR1tt9FDU2DEaZPR+RKIMcllbfzNKQJ9nNhhsNkk7ncmItu7qnJa+MQTU9F2bKjtQAbG5cJNbblGDrRFWCmY44RhgA2YdxjO7jhqaElC7jtCvkL7/tB6gtpqYW58AblJ71CmvyzuX144GXHQJRnP87Nk="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
