# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "a165117d032ac3be7bb27b34ae564ae48a19940481e7616dffda9abcd2ad841eU2FsdGVkX19eqmHPWx6w1K37MiRisiopvdPIm1tuDL6VoXykKn4IlLVvIq5FrzwvUEFYbwa5Bfs5bu6uBlbJXckq8Syc6exISqLKj3TtxaWukfnYAelwtpkCcEDxZD0qhZLynHtqELtj2nUGL2poi4txSkGMzKhqvsRoqkvR5LnD5Mqu0zQCld5pNmUKsvpp1Jd3x9amYh1y/oYfWL62Hv0jIaJ+YcJiIdJPlH/4zqkqLLrXq+MKPid+/9YjRRbF/mT/KGtsKXrdbTAYy8m2WzBZ1lJNHbeB53WAKgV2ZcZbu7HZcj4mnz08u/mQfpWTV/UuP5j2j3BLtvu2SYwNBkLPxAlDwbA8ui4lwjU22MM6DoKtDpqVLutJhvVNxsm1j8YWSHrLtiZRmA7ZqRCQ2rykGTRVp876y7k/REq4gyXEEU/mT1cCmAClRVXmFqt3UxR5Lb88XDjEhTP/VdIDeQLS70l4eCSZ2nCCnMGVALLcLCjIlWnWY4b3abTeNHT+ccSEzgpOE3OB/+rf0GUxW7CUsiZFc/C3b3uagTl9QAQoZ580HGbk4HOi+rgdXSllVPCIwrUKWpysrV8Ceafffe/XMTs6HDxKK+IhcY8vKsWRnsizkK4R5z7Xf99S7m5L4P4fEYRMcasUOak3CxByEmxvLAZ7RtwjV8xOCHE6vAmnUu57x2kCeItVkKG4SbIvT+7LiUNIIbsuNtmTUCwYeElu5FV56LjlIioG9yKBZymzOss428U4Hhk+imRU/W/c8ITxje+RDF0r38XHrZou4b/3P8AWNtup1aozKO5kNwn6pT0s14w35h4p1zaVHcLN7HZFK4OrXLWyndvkOrXdmd2ZaFbpOP4O9J4XB4sGpVyyU53Bs97Aus4R5IFZLfLmyXuySNhTQF5W0C5hAkIExC4/PYSb4h+6P0VdfWqWjgN6Fo2UEtaiRPupYqBhSSmRVM4/bVxVIldUqZwKdWnQFY5QGMGLgmnPEKJ0fz5rkpAvvtaiMK3MvdCgYhvRD5OiK6SimFLlvV4VprnXYmrT3d0m+ih5pW0sDUI5OWudyqfKJ8enyGDGKklDc1rEjMS2llk+Uq+s1dvOCVxFIs5C6h4Gz7kP63CmNhQvXiSH4cMtAip23hOAY2JUccm3u/EbYGRNo9xzCdNrLgP/Mx2UCnT/sGgeTbumszsvEalYwBtYtqxb/x5sMDDXkuRMpJqAyJ986L6oHnLOPXEOkO5nHPzWdCeFDnmUnYHWavJwcz4CXfz2mZjn0p+D1LYukTXOdoGbbFgv0nNfs7bWNmTOBNV09spxYoHMsUXA+Hfoh54SbepEe1OTT8eIV5jEbrhOWgyR5Nqfo5V+HiXO8whGfkFXvaZmnXWc6fPbR2ZrRFa0xlIcs1S6vemnSnr6z6l+JH36suI030SZVIWEwiz0gDysrJ3YUCDhrmdcIB43olhZPcASzwvXc6ySVpuhjz1ZNc007No/zwaKhEBmQtUYkkwMzkFlLuph85NJw34wt4L8FYAeaN/F0Z/Z/VJ8G6jyC2LXG0BeRvz4GXV01cmWpahG7GaeQVaAkMWQkdfbBvWNxcfQshlMVzXVanFSE5+YlvGgtly2+F33gHj9bD9kegOz2Z0N3PSLrau3S2AIwNGX1CH3lh0xJC54WdqwKGgokUz62fXllKf+QlioaEjLOzC439oH7BuTl/HQNHlwxQHcobEa7ROoIVllPOOuhz5u1XF7Y0FpHtkMq25HQvE64E2TzGndOUQvtWzepyyjU56Lv5X3BIj1p7PH/U3HRKwjew9GgWvrYWQmBxr5F/0wOcVOnRVhtKc3hz1EwcSaWkf0bm5iCYssX2UMgmVu0lVC5V1pF3y+ZfBC5DkTobML3899FqDFQa8eHrpQj+lh1z5snw+Mfgup+ethA5h5tGhjP7z++Mm0H5C6xiTjdqqHIu1Kh3g5BWTqS5hjZ9MNCSQ67GoNqlDVFytnwe97V2/MoPn/AP9UOLjoFzs1u7dYDWQMsHS2M6brEn2iagQgSlljupPMMJ14Y8n1H4mf+02U0qW3iENGFdghZ3Fi5imkyFNuFRwh5ycUwZk3dGBwWAXtoXeiKZ4g3pkmc5+CS9bE8yI+EqLuoWIpiOdbgi2XfwV0++BNrxwEhpdW6XGo0eRJaepze2+KgzLYF7kA5NyeIWOXz8ah+DQolwuBWLUVmo+NzpDdEMa63YWV2itcW1iia/Sy45MjtUoGY8nD6LcbRtfOfnSCuBaCfAyk1kGMCyVocTVAE46WbQ9f5E0eUOoDxR85JXp2kC1vY6Z6j4pVukj/e55/IpdwH74GMPrJpECnkBMsHprF4Rgm6acI5cewIH7mSjo/XqHVb0H0s/Y3ydqVTQUjnO1jUUCvNMoH2Q4XV82bOwd3gRK90zAp/J1v0YcsM0WpuB/Dn/ZBw25+wCzRadBjCNjIUJv2VNlqi/55bqE2DO/UZaI55Ul6lQdWXKrKsWZ2Dn8igwCN0f7vH5onJnAL674s9BmpnP1eZ72hTPNBH9iTr6hD90unK6c="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
