# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "3e7310f005d1acf05c3087ca16ccaccd95ac87948806b29486bd2cd238b05fb8U2FsdGVkX1/CmCxCXo9OFgvyMcxGwst4IjT4mHQegvuIn2Oc30r5coKZOpxenzsDxaGg5kNaAi44etgXTjaPnm/mxMCQNGzCy5sfbo+uT9d7vxxTIH3Hii7qqmn6kjp0YmMg7yJFWGVZQmcWpq5SvXTckoYagWUbBFurl3BOyBwHeY55SZD9TM3/1beAuVPpMORZS1OogE6uyr1AlW7MNjC4q+r4920sTWEKVCTQ9vKcwPVg5r7KJ6i6PwnuH6/u2T6oye6ZXU9R1rRfuIU3cqg46ONl+NnY0SBiRmUP7FINK3U3H4LwfcdA0jvFJKRNgTtBdp52uxR2Ha3ZIhIMJm5bpS4x3v8ixKqHoFXRFP62svBufHhU9faxgG8//0C9fB/Nkkx+eqaQ6uUqPqbny+4w1k2tTPXCDkW+I9N0QAlYZP8DkKqv1bgpk3iLQl+xkzoZbDrPJD7NwvnkF/dAgYRSdbkCld8hAJWh5Yht4uyq6XIqgDt6j63PC5SnUrZaWNZwVxDKKALqjLSShXULhTLEP768q+EfiN2g9EYUYNyx6wdq/s72uLmvZIdDW28zFEXSsFk5yqMoAFXtcaUyylEyBY/uosXAM5sNnbbZOLsF+qS3I9PkBo6YHQXPvoKOC/2F9v0/zISyEAzFoJUmoAxCPYfgXNfafWQWjSsgsUt05fOi3uqNwZVHzo7bZd0TRXprIT3UHOa+o9qeV13kQqmDsHE7fpDSOkCO1qbQDLrCGyPGoo/bxJ8FhaOGM9CxD7jmYK0m0oMhWAnFAa7MC8ikbG0whicybvYLG2cPVc1kkYb8C0A3qi0vadMJDtTIDRpga1vF3CQQASgygHEMye2vcVP8PuMZMXIdPmqIE1M+vB+k0iBtNCeSVW0VVrDWrS+ahJlWfzh47yqUgLRlV84/J9ArRDyDkl9UXlhkkUl7ocoWqEWrTj1g8g9FuBLwjeCjLS/LW4PyVnm1CqBDOrvOgpjz8wv4A6lsIO8SULV03YmDaskdfUGPZTI8HXhWjvqqMVkzWVCcrLj4Gt9n2IZghsnfD/7ENP6P2PPSf9jYDRc2I5DNWDrQLYz/eQyAxKgpMB8g7JFMVCmvJDl5Wii6b+DHcAma4JQsxf7KKrmoMKi/HfmsvzaPyDtnOymOLgRyzPI0ur3LiS9rSC0TP2milOAOUlRS5S15ZrGhKzsqhkc589d+TRYElm+dneD13518nRmX1BAcvF39GGk7LXWmsYvJd1kQEEqewzs2A7XXsoPrraHolKwDnFKZ+j7a10sGYEgj1fU2MyNJoczIHdC+L8hdmaHMNtkvPUBUwLj3J0h+jh9p5+5D4M7sDHxTrfImJ1ieEVTYzSNDGl82lcaqN7Ak2tYtHCIFvmAZPczPAmS1M77rPPY0NJgERYELq9s6B6z1tdqkqKfxNNjUBLIVtnVKtebBjmopXa+IctQiOr4DHPpGAss0yos02nU5zvf/lh6u9DR5f7EvL/4477TguAM3oRd5Xv2PXPNlplFDKD1dnBjSOsYx/+xYZtp1FpxPpv/xznrCeOmKhggaGohgmDypyNdt1gbOjt+lTX23lMEQjoLvVirvUTEHYCR4NVA1ptegtIAxX0fKIYYJ1mHqDqNdJvl0kmJP9rBAAE05PauO/74w3GCJFyCPZ7Ody4LqDSn3lUeP9MRurVcnBjwLyVM/BVQk0yTrQKIhOc4XYJL+jj+ft6Kl88WkzWi1C+rlgfvqjFkHiBRQ+zLSyhct/q2CZJqGf2MD2aky9VbwgHyOU882mOx4W6k4kLKW7I2S5vWSFqdfy3OOl+kwEHjkir8LJcFy3R3h0erEOmHZnJ+Amwe3R7VsYIeMpCntDaEHXvcjwX71ONBQ5r9SaX+H7jeuJwugSTtbiY56bAwXtq9y7u/vjACYqUf3XY/dydjZrBpe+wZmC6htPOEQrgYOuM7qLJw2GO7CuT5BKCGMxExgoiCz3tCjpEYazipZja08fYnP1jrDMVIoEJnx8nPPvbmL0feb9ik9OXSWr8LnoQY8V44fBI/TvQoxjmQ8klgBWsYaJx6S1c0zCVszCSvPEwgHUOU2qUohOKBpr20nleuqLLA/Hr2O9PwV0lmxiqtILA5iViJ8AYbVN59SgGHd8lbDTsEKdGmwdHflLZB+OqV4eY/AJV6ifpZJ6zP1tyDPiFd8Kmyc/D0wTLHUxGwdNIs6T2AqY0I8xEKhZJYReDFebGBPSBltAU7ONh3dcHvNtBbbTVqvLMQWL83/3fBMey3lE+XAGILKcVmAy43G/PBm28sihvxNrPj4W/DTx/lsfip7LVwdjb7I+Rt72pcG1a9X8uDKLCyGi7kKXDfNBgLnNJ3Dbsqn1a7DQD4W+bRZGFncq4dPm3wlS7vcsgw0VpRhOIGxKR3ewK5YPwfeH/d07QHlAVeGbLV5dl2CnQcHDvTAkyXfLxZhCLWpBXttSHDfKdym51OwncW3e7x16mh7NPjVZEU/C8mHZfCLA5NwRbd1qycWNVEfF3l1EaMpRxhYnGTndFNs9Nl1HD/O6PCIUh2ko5TNkH7L02sFTP13/M+U7DG1a4yi2utdUuOi4FLfNvvF1fNLts3vpGKudsOHVUOR4LX6m61vs3jKddD4NpBL0I+56YQFABImPataFT9HbQMu1YYhXFF+ZATBfvCf1eC8jw3A6ig3aHoRlsRwygfzhtpS0EWz6cIY+gRirKt4to/bEToTEnQoAMXO0NjWb2lA27hRPeHuWIYNCQsAqalXVE1Ici64VLlWmFU9T1tI4qTF5xM8HQR66BReGUQLsz/X3yeRokdlW41s8LrGpsaxpOA+R97mcbfrPLlirzcn51KXAYN1LLHGmT22CuoB585F7AaIuI4Sc8WDgZorFS/QcZCklaVvch3Q57fQ0wEBE3ozMbAZ/egPTQ5H9ObIsl4OP4zK1eDE/wx4wPkbVmoAZ8cO2NU3Ohzr/fo87e/jgJaVCrQ62UrN9BJEnHy9oo/hzWWnnc5g4w2RUZj1TN3o/lAKE/f2iqMjCGwZs5PrkDCJsRJ0OLUQBFJTVwxgHFXa5uOfMgbuNECQ4nyQIi8qsbQ3dR7pEE/rHA=="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
