# Hang Out With Me Config
howm:
  title:
    text: Harriet's 16th Birthday Party Extravaganza
    description: Driver's license time!!!
  details_description: Come by to the house for BBQ and cake to celebrate our favorite daughter's 16th birthday!
  host: John Smith
  location:
    street: 4216 Doorman Lane
    city: Jonesburrough
    state: Ohigho
    zip_code: 42069
    map_url: https://goo.gl/maps/877HcdHtookUHhjPA
  time:
    description: Going from 1pm until the sun goes down!
    all_day_bool: false
    start:
      year: 2038
      month: 01
      day: 19
      hour: 15
      minute: 14
      # does not currently support timezones
    end:
      year: 2038
      month: 01
      day: 19
      hour: 20
      minute: 00
      # does not currently support timezones
  contact:
    description: "talk to me"
    phone: 1235557890
    sms: 1235557890
    email:
      from: email@email.com
      subject: Birthday Party

# Jekyll Config

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - _events
  - node_modules
  - .gitignore
  - .vscode
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .tool-versions
  - Rakefile
