# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "88e27aa22cc083339447c634e9f976ed00a522b01c52d9822b423898db071276U2FsdGVkX18v8zhmYzIFQEVIhFq7+AxgOw1Vk9jd9f4zHzNNieqrsveWCmmHd3rwDXWkrgbmaCHAOt4pslnhhqEaDU3shP7++rTDREEu4Qq06lTvx2ggc7Y5BTcKVMa7q5YD6KSPPPqMzNKpqWEJqPJMlkkproYosgHnbRjHxIb4M2hIFRvIqKnObNr2fqNLDysloFYbcLZ5PtGx/8K84XcJifUIrrKiCro2gSbibSDgEqASkg4QuQ+AR3+8y6gp7O1VjOwWw0f6eueClm2eRUr9woBg69chYd6lFnutRkSx2Ta0dkr4McP5RxFjxcALC9cvybMIMVptR1S0HjGf46fcGkdeSXijvtFtM2fA3cgtphjUZ+A2d9snUf8tdPKqKZS+CJDW7H/vXitUwIReURhej+OKzkK7fC6/MHnUmj4XpwX9W31iiBHVvrLW5zSWgLuax315b9OPEneE0DXUiMMxp2Aq9uNEABweia0zDETCg8EtBATGGhbkmA2V80x5gdZB1YRMLgdemKPxfddLtcQG2GdFYsF0z1en1lkyPXXdnSPFgem8QlIoAmvQyMYr1N5ySTuYbijsULlT5b6ZL173gO7Rt2KounVCW4wnMhftF6LyD+SQaF8iDVd/Whg7kO5ZvBjpSy30meuP9MZpgC5PXY0uzD7JTy17D0cQ7Chzqi7LsB9RfmOEyocjUNjhz1WJ9mFFJGW5hWuyk67cCiPTFY/Y7GZt3ZmaaQQ5Li2cuZ0LOa09/KhqAdViOSXgI3YfCXbNWSgycKe7Bhbi/uVwIWEbkJh7dq+wr0P5NTGWzK5sFb/PJjd6WArWh8OTL6rpC4Kh9bPuqG1IqcjwhFZddpQ2xDZqcvO00NpPPNtaOMUUFQ2mJRoeJ0aj9o/FUrYGUKKVnkXm9VDwhG8Thh0KcBva3t7/RcSKnpvSWM164h1Vukd7+hju9Sq4/y3r1SM2dK72b7IpfGTEVHPnPe5l3K4ih7e6ROzeN/WlXWGM9hsN5N3XY7fQ0JhdOTKZN5NZ3dUR/twOgyq6Cu7sSMKt6X93aKN17B05ZO+2dwj9ckGyILDzK5E/MSSKFqZQoXDy0DOlyoMAdh9j0d4WuOqZsKLWElpQloeWsIQtreQzfqwV8+NVHG7ge7vT7yxucM3hfE8pSwxijf36HjKdzn3RbAjhWw52AvjzlKS3hyJS9sNSASlrzvosSOtSo2xntUS8N/HAC6Zj1nwJva5xuaphxsPF7k1OH9KoxTbb35PkquBPJqxAUyjXJWGuV6qyS4SF72+wb+znkwFS/9cy4A9/UH5vN7tb5gZ1Ko27Ou4aEw7EoNGd3VNBFs+JfuUVT2ZuJfYPWegQJ3QdM9Qg0EjrO76+hBIvIXvhRlEkwfvLAhYkDxhk8qTmnWyyDEvtcklFx2EAmuElKfTKtHpBpmZn3lqjG6NuTX8f8MHfPuBFELGEfdiITWpyVE/zOO38jQmK3GZ9Aatu8KSj6OOIR4jOyhRjejD9RR//gPfTL1McqgWy34lbNQNNhxzRLLAKWbluA+LwfZA4T7XHkzIBrOVibrt/IK7kODgy1/4YT7MxKdB6nraPBG3snrBOv6jgnh2yWu1vFFlq7q7BzhQcpm5a29scFjL5c45j7iR+OAQCxlun11uewEZ6HJCK6zqWK6x9Slmz8/XSOSd0PQ+PiQKfqJzKsFqXR/M6HaNzCgofSBUOPsbrSc5olpBM1L13pGQr8lUQN96cKXGDYe/ptFUKgGkLjzHufw9NEhiuInK0YX4LQmIt1ppLXBEh6qYJeVDT+tpQFUGrfHfdI2jH8NVjr4kKZAoErBZQ5xda6s6pZcZ3Q8d7BK1O3uKFioDjLT5+jIFopPtuM4z+ZZGPBzTEfAxxCZVGX1ZYoekIrFgcbFQ9M2+CF+k3SGYCb20qwNr5IfMZumy4bafhKdves/MYXZ3OVLunbD2k65er9dLKJNs5Z/zgNya2QAgyogRe8bIFGRiCiVfVHDVIBdGycazVvXIyZWuV2VlgLvvriEe+kiQXJT/lLr51kaKG5vzWsjDZR9ROx4giRVfXy1HSrdGtxxZ9enTZk51Gz4c8UzZMQbRsUJy3so0Tn4dv6TpviYdzBPFSkjrqxuiY+yjA66HAWRXl3ZkP/pc96uPfdIky6chnhUyxeN+G7ZvYRQnzLAEn/x4zkteV7tWVRYf5vXirPSsmJbKlI6QJ//eOJJlTzhGTD3xUKpvJzPbZfSfkwMDRiDnTLu0dFbexH7JmExDg0gTwsy0x48Irt/+bXYljqmegfaoUMBNIrXgaKyvIfbzGSyioeKbxqMjJUtNhJNPT8qHnZ9rj+8pR21AwKqJ/CWFbxeD0TLiYe48AJ+JR/2onEfOlRsl8xoLwNVb+tNSn2ZbtkuOZXOd79UxKoqACb7Prhapptc+ccJ8OxMZ7u1v0AqO4Ui2/X70rp752UqYOTe8rIsLnO5jvCc+x3lAFOc0o5SwP0qvF1xREkS9YwL8GBoGLVVNpNctaF4BDSMd5FLaccelzrKjE4ODzkg5l/fgPEs771M+/hP6XmBmLy7VtmqEA5SmlQIhy2JTb+BuzRtWDy9hVwP/10GVaqtGcRDwE1A8T17xrL1jIhKkjtPFviaQXrXbpX/taTvSbnJzsgCz42tEURcXYOhnKO21teiKG8pSXJWewZBdnNFHeKgjI3AKuBQEQt0qhCYF6fhy7uVMhr04boe3IFhSjQX8fWEtDwbW2PrY7NQJzbGIeZjQZlJyS/dm4KF29yraYJ3eggdXh0I928k86XQVNl7dnPCvKhvelMa9UzGZ7JHxwxO/OpeZk+xVDtseNPTagTEmoB/H5QDS9druQSUmcIno="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
