# Hang Out With Me Config
howm:
  title:
    text: title
    blurb: title blurb
  details: details text
  host: host name
  location:
    street: loc street
    city: city
    state: state
    zip_code: 12345
  time:
    blurb: time text
    start_time: timestamp
    end_time: timestamp
  contact:
    phone: 1234567890
    sms: 1234567890
    email:
      from: email@email.com
      subject: subject

# Jekyll Config
exclude:
  - _events
  - node_modules
  - .gitignore
  - .vscode
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .tool-versions
  - Rakefile
