# Hang Out With Me Config
howm:
  title:
    text: event title
    description: title description
  details_description: details text
  host: host name
  location:
    street: loc street
    city: city
    state: state
    zip_code: 12345
  time:
    description: time text
    all_day_bool: false
    start:
      year: 2023
      month: 02
      day: 02
      hour: 13
      minute: 30
      # does not currently support timezones
    end:
      year: 2023
      month: 02
      day: 02
      hour: 19
      minute: 30
      # does not currently support timezones
  contact:
    description: "talk to me"
    phone: 1234567890
    sms: 1234567890
    email:
      from: email@email.com
      subject: subject

# Jekyll Config
exclude:
  - _events
  - node_modules
  - .gitignore
  - .vscode
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - .tool-versions
  - Rakefile
