# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "620ce4e6809b2e8bdff8e4f5fbcaaa0fa8cfde607259d50af817e6f9eb918ea5U2FsdGVkX1/DqDPMv8s1OrI/yS47ug2enT5GUeLZmAhOwSHyIgwWB8P+6ntFeScJZes2/zy30WgAcELBN7VgeQ3HYK9ptAUdTaHQ1KE+4oMEEiUWU09I5mh/A6Yf5x0kV/+zn8fX7nfqcustbsMGYreNRkDhxS4g/jH1F/0dCBV98S+YtEvv0fDfWY4QQurrZyvlV7zax4kzmk76pWQydSdiIIALpHE5anRD4ypASC9CC8dc/P97GlVvV/IEEfJq72gsLR3iPNXxxgMByNz7aX9uwmepLy9yM4AZVwHFz+Gqw0XoTkWAEK185VaTbLuerN/USFJ207qS+BjDapmp7tog+Tokyi5qaWWgjrZ5cwSIQeRJHGk6AyNadjJh6Cgtezxba19tf/5XgEqttlLRrqmKQupSX7kqaJTfSc+i0CBYnTmNdPJ/MG6vNdpNpgAdENU75PRTbiIw4z9mO2Scu+xgW+v7/b44jQ9R2C3IrKSNgWjZ0mR6QqwqBgrfLCHKCz3NAYftBdQXSFiu5zSjAjVYyBZ7wp0mZPBhBR0QYNdBMtb8cR2rCPp/8ljPqfgzOfwgkyIH/8Qypudgpkir9YPDHwbIr144RGR04gUsB7+WMN8mEcjAwXVuALTbdsiDNu5sBA/oykQpWV3+2Ca15SQglonmXmCQtMp5x6Pe+xrW1bnDGJuASLsp9RJPXNL+IeF8vQk64cB2me5fQTFTLX5JuHEnxXMKxsCKDbyOjJRco1ro8ITkk/dZuTiGI1RHjAt2VQpS6OhDzTC3jaVzjpCwVFUCC1UDoYkCHBQcbjBQWNlLoS6TpeZi/7K+8/HRmvQ/riHFBFE/NSbaXnwTF/Q5z1zVPpZA9cX0lgKzea1PtPal1YokvMn0NKTXIY0Re+SsgAWA9ftyfc5Z2dNXE3dCQjcTJxToHnZtK+0CH+oJVRZbFWast/AwJmSsDokDh1LlTYOjUAjuFBhUeSn+uiMb68571/iTYjEhCnmeInK3gLSovIwlVzI5J2JyoGcbRuea1PO3n2TZvwI/SZ3hklLrtKMqSbfRv7pCd8A6OvzvEAeoA4wJijui3TQ+jt51W7Q1zwWv07JmKQggzF712Mey6F69xMGgqEeAXd5o1i1dKI9GopFNe8fnuT+AZjKQmeILLTd/xakud9q6gFR9NVFu9yO4Ai1lQioZ/5V4X6YRtc1auXf8L3ZtgZCpg3Q3X0/0pUG99see7IgGBMdmned1gYGaMVn5ImbUhTxmSz4UM1fYQnE5o084LiOm1sHwyb1O9iDwQ8RWJl3gWTI6VKRIYb8dhyIWpNUtG/r3cxo0PBKTAvai/cK/y6XtvQp2EZJnjZZ8sof7T3rnWvsV/OdtL7ERsKbI/WGD/wF8ZuImACZxp/tj2hGLKnvSXRJ6CWR4kMJRhahcDCVTmNtZkGxbPwZT9ql/n7b1VUPrMOfe3A5JqG8QpxZ8EpouD9cnB86NdCzrEIX9MV66VYM6NrkCIuY+uam99pG15i4NreotT6CNNg/iVpGKgX9cCVn1JsIq5NmPy7S+Y3CMPDFcY9VWTHLHAPW19p9R9cB7qEnlxiyLLX/vdO+mXSlrijuHYURJ8xw2mVSMZvGBJgp3tHVMjPXrtZ/OGwcR2CjiDlqznaBo0dxG+6yFwfJlij7Xj5D+mQg3XL0alw+8LLwem04AjMfeBwdVfbfJMGrYl5BnvAEapTQmUDTJ0cuYetV71CcucSjbizwf7uzrANCNGU1dbxKP6S8TrXwiEzbffUl3xZF/2c7rH5scJZkRe1mAM6DeV1y9hqzw+T9dzR6f9TeaH5rIDZoZWBUve1y6AH8FxwoyBy6CLkP8LIcIExmbO/kOZ/PV1sz6sLyUUhND3xyMkLWJVK64k/SPNF9q7VC4rGqppD25hzoMyGZOZYxTYJgNicR5cpZFW9PADe4DryEqz8UDV2x/mjvfftZsYUb1oYlYeE5wdzfgbAcfW3gMXy0yNdnxP3Rk/2Wyl+6snpdj5YydogMnyPpFfkVb/2YrJOA3wdn7rIW7tjO1P3SBJSG94Onk5668iB8lP+MzDv70/trHstvtaWr1Noir0GhGLsgamzP68d8CdENTg6AHDAU7sxtWOzA+4EAkoLhqY5zMuTluclhZYzHFKxRz6GeK+xX2/n2XTvYsP1wM/psAWo0Qcz5i+I53ViugLB+VaXkJa95OClFwXn4kEX515iRuf7XmVUU7AENthG9kyUcxiOiqfjIZCNNZZgfLS4o5Q2dB7BsXagXGoL9lOg2E+wTLaIUK2I0P9R0DBhUjxWDCbbFPIDCrzgVDd/Pnxa9TbKPlieXVcDJvJC3V6D5Un4DX1cpz6LO7dqL5fW5WkGa8Vz3gD5PRDHDNvBhGo33HeDXYcilIWyndVZl4JcNq++I9sjB7V2VN3lBzBv0MHDtixqeXhQ31Sib9LtoKkYJDrXBUi8C5URQ1liXy9RCo/hgbubbnKXvCAutob+tMbVys4iFA4VdFhx17l99/ntKiTFi/xaEpqfbJbMi4wMtL4II="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
