# general configuration
url:
baseurl: '/hang-out-with-me'

# an avatar or logo (optional)
logo: "/images/logo.png"
title: "Hang Out With Me"
# tagline will appear under the title (optional)
tagline: ""

event:
  host: "Eton Doolittle"

encrypted_event: "6d4cd67c5db8fbd7f7e7afe9e8a1235eb59b3967b07a08979f34e13f3c80f9e3U2FsdGVkX19r7plCn4rsPIGOZBS8YmGRuyMGXLWV8IkTEga5nbyTnNNVeKqtAeW7NXK7/WQBe4eC2J51ZbfxszosYIH0vM8PCUg0ye+Nol509pZBwQnYkPUf7NrMYMifBqHV7keL8M5YFm/KPQbZLseatfjeM9tTF/956U670o8GCRh/s4LQJfmgPQpTJVQ765xpQe5fIwscnw7K1vY5eEV1FFUKhJV0bvjS8yhcw4eMeJj6dmlUkgJlO5Ne81UogCOvAt4MDvO+2WvRCZgcFLz4HrPbCH+PbZcPNyoovoiMQAz/gIAi63iuqxWtLs78ZE4lc0J/+Ld1g3CyrbROofwagh3bwaRNHMod7P6z3SGq15SETbPckO4EhCBsIrWoBh5ZBRK1EZu0DQ6jeBegQs+1D6T1ywYLWhSJo3FdkBDXF2LcHSveQneGO+hJSYO1iu48i6v1hWWZ+WQdTss5u/G+2NwgE+5zLKKJzywzTE58/Pae+dNzzgZqWZV592FATB48+I05dDJikuHyHqbKGokVMYyAXjOk5bdGoY0frqmEd/seSOl/Eswc7QP6c2ik60OVNDh/STpsQjUD5RkdVenskmZHjZ6QvPa+OUvs+f7Hdva2dv1vu+q5gqP9+Mhi/VPtluZZhH9DxEZKMo07lp3aj30fcB1dhTrKGuBoULpiYQYwuhKuNLKEvhpcgM4g6ceUNh4Onr3hle9Jny8XJgdZ61GQFXQ0d4odXa2gdRiFfFxYoK3WvpczQT5Wzyo20/l4GhqYdpcVThOuOLKomlxmJR9AYBQa6YJBZtHtDfIWHDPzBamHQ1NrJ14hpPQ8jLoHJjrwidA6Gyc1/HhrtBkAo/2nOwRe24xR5p0mOyLN3v0U14pIsBh6iqiV+yp+vJT/dg9YZ/Fk4auZK31R2tkNdswcfOBNu1shco4aN0icVcFyHw2L9ufpW8rmRPu0apuUoh1jfPtNEfAPfkxI8v/BwcQGNYPM42RatTEtWzfKfbOe7W3H/7Cg72dGw7KebMzqS5kVxBAQiHNMOyT8p77u1B2qeicDnpBpJUUjpL3hL71UrpzUE2ZbCq0jkXncb0W17zo3PlhqdmUQ02ivOXvPdm59Ze2w2FvQJVga51hpbIZX3MmdFMZZhN4r6kra0xloeLbAnsTbEobktPuQMDvqMEGP8AIRVQN/nBKukykncdAY0DUSTV/ve4rzxEJoJKrp2todFOb2imEs2SmpuAi7aNMx9Z9mq7uijXqLtI2hvb7a+lhIy+u5NxTfHWmokAtPoJI0an2dzJi/DPxHT8OJorkSdtwAlA9SlytVWbHG0BQSTq4c2kd3CnRbnhteTGxlJXn/irmoGb8LIfUsPvK0xiulI3Jx7hVeyvPf2/zzLTrnSkys7KIP/LhOH+gGVDWRlWseUq6RICqjQ6Lmc0tN2hDyKdiLas3tKCAlmVk2o8Mvi54TPAAoP+YMrEPvsvLztX7CM9+8RzjqLhrc6aYAJNPgHT3deUtT/TgYl/01prxu6EqX2uk1gyw1rqLgubhu7MPCMteS0erc4C6Q+/z+pYwrUYBaH2oyWoUXPoN4sDctVoG2dLO8O78ftqCnhSWlq6bBuO6nLKb0zSPN8+K00tNtK3VGJR8pmYUOgCdrF5d9RdDq28HbZ0/wqQ4mLxulS3b1oFgZb0DQlxcSM4gKpZ/O6xLDF2CAJagU+8tuwyOVnq4Cqr/8hlZ9NLj3Ep4w8cgI9RLHaY1Vz3wvWGbYfQWAWmyZseTkf7WZlGKpNjcB7mXlig/vzJXctpFP"

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
