# general configuration
url:
baseurl: '/hang-out-with-me'

title: "Title on the Front Page"

event:
  host: "Eton Doolittle"

encrypted_event: "155b1b26ecb817dac3407e06df463ca84b9688571a6af1064001626f78531c13U2FsdGVkX19KS9zwVEDV2Jz5K7ldrhdPuskJwLdd2OzkYV2uIMMxQzdXBX9lYGFtmFBdDu2qt4RCLzpNaSLnCzmbDnOkS4Fheqg14hmTdgdtvY/4B+NvxHvxq+VLSLQiXNBDHlc/WEvMJX2scBHp92/oYqsYDtF3qWod8O2veYRsw/l5pR/gqC9FuZOtXt+hKXBC9s29xse6sJC4Xbn/lm1Luie/psiQsBmRlkYI9RKZfAAR2VrAWJ0TW71uorc7+2npMW4EibNNYt8Ut3hWCsbfO3MZCcuLCs2+qR6C7rovjSWDzCZ2ET5naCFqjnwfiqsF7skC0Kkfx78fvSaYmd/2Uykj6+KFjD7VOVJ8U+oWVkFZbbTdeVRH5CikHJm0QRm+1eh35tk76aiyGLeuH9kldmicGNiknk1sRoME3Rrn4NJLWXcPOKKgqDxF5P3YjGdeUU5xLY2O6Nu0t+EwIBHC96CdCwfo4yM6Y1Aubh/4Qcpf++SWetHHlWGEmzcU7Lglh+ioMh/QUKHvrA6ARPuRDz4yuUNcdsq6T3ZoiiK4kfpsV5SJkvf6aOd0C1Nc5Gpbc/SyHIchL/fM8PXHg6Lc3mW5QZIQOJWJHdjsEd0ifIX7wl6AdZsXeJFkLhHN/eJhmjvOC+EKJdonpkqMhLe7QG8kRJHIiPcU9UIPKj/euEzM5DBceDgReqi0VKwdcJmdip7Yvth9B+T3J1nQsSqYSoYJ9b2i4zzRc0ifYJea4FKOKaSjr8hPduRT1oECA+BYRqqlXLlpj6xYCNrL+GxyWDecb6OZeHTj+ZuKVLzkfH+ujpyQNpBUuAO4Vm17+QfU3zWXP7A9QBUDKfpHRNviRfph95GbIfDFvKsZIcmx8ynSJw8FfkxIZ5hmf6s0Jexf2MiKdxannd7hG73Vt6PWNsBLQ/VV4oyX2ZnAtL9BC1ne8MJUnIcbXGVlRMLC2l4rLwsbmnAZDzihaLVgABJm6uTuqxB+miH6i/ijxZlJAKq6lOodBIiXZ0Uk0HvoQmGBhYhmOmLw2+5gzVmalRpQQw2RPPNX+dbmMwpK7sXlTTgERjKjtnwYjDHh5lo8XUTBNwIuOrD4Aok+OYCx6DXa94aObKWwXKSGstz6x8slkI2h55hEC12BRMoQHylLfF3VhvyVBEFkFHV82vMbCYsj+5DMDkofK0fEePNCHTfvrsZGJ2lBtUpPXIeaLvkA1LlzXi2V7/2hQagl8IGiKrMII3oz6joW0LYUwvjyCSZ5dvf336DUgFdg09MkC9EQmq/G3Dd4AIv74vBI/VuYd5DTDE1LLwGrYL+Rkj/bjSrzID9Bxkb/drdz+n6d36bqY6b5+1BXeBXeBCUc9iXeRxNPGQPmW7HKzroVePJ08rWVH08cFxbgUYiQhoNMStjba3neYB8OeQj+GqVkQMkN48o7nRMpxt0alLje04vZ8vb5ziDzxmyaJcVzK6f7eP4SE9j0HvAFWJM+XoXPLXM1coljPHGmjIsRCQ6J4mK+VAIt+/8Ve3NeaIy/OUrl4Ysls5e8RC2uzVWiiRUTKBwk1LUzGxrdxPwX7HtAMhrhTZKb0imiYIyOOOLzAq6V2N0dUhCBXxguYq9z0mdKRXAcHekLyHAfqwoc8lbScYXkUIAD3cfFGyVDHCaIwdC9fcSJv4kDYo3zdZ+W6CmtF5jSzCu+k7V8kUxevTxpzsc1J84qDBk+FpT1buBzo+5zMB+4Gh24kccy0FrE4AeQ9R+QdNN+1l0E7wzffejysUi5g1pfopfGIc5m4Ibir6mM3Xt2XwsfCVdHx+CIU76iC/KzqTih9fFzTNNYFPLercOw/0X1qFhdkVll7YSuQ8UYwHJdOzK2UAMh4kpfb4oOKWpbCHUidg3ifHdf1ly29aZ3WMAOEspIBvINC0if8Q/3UBrlD2fM2PDTLf0plHzKoSpvDyD6SRMmptA60hVdh1fmx5BT4gEvZD/lOb9s5XZDDlxX2d43ty6dyKYsrJQ9+PjUYFoziAplyvonrKpt77rRSvY/l0B8Ls8wjPfImBHz+dxqmrMjFKm8hQj5upnw+SzVWGBQKvrp+54DaWSIYsGYT9rYxYyOLuKiSt3NFNdDrCp3ASjQ5rUqZ+WXocSsibfZHd9FoXHXWCYU9uL7fjZVgCJYbCpfXgmzi7yhH9AOVkz9QJacq4tI2tsqSgaa1yT0jWRnjb91OkSU7I+a08IfCDA="

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - _events
  - gulpfile.js
  - README.md
  - .gitignore
  - .vscode
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - .ruby-version
